### ISSUE TITLE
21-04-2020 Team-104-The-Fornax

### ISSUE THREAD

**Issue by OdongAlican** [rajkumardas2701/HTML-CSS-Capstone#1]
Great Job!! Keep up the good work.
Just a few Recommendations.
- Please use CSS styles of flex, margin, and padding instead of bootstrap classes.
- Check your site with the HTML validator.
Great Job once again!!

**Comment by rajkumardas2701** [comment]
Thank you for the feedback Team 104 the Fornax. Suggestions implemented :)
